# Generated by Django 2.1.2 on 2018-10-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20181027_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(null=True, related_name='answer_in_q', to='game.Answer'),
        ),
    ]
