# Generated by Django 2.1.2 on 2018-10-27 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20181027_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='answers',
        ),
    ]
