# Generated by Django 2.1.2 on 2018-10-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20181027_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='background',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
