# Generated by Django 2.1.2 on 2018-10-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_question_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='u_id',
            field=models.IntegerField(default='000', null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_in_a', to='game.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='answer_in_q', to='game.Answer'),
        ),
    ]
