# Generated by Django 2.1.2 on 2018-10-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20181027_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='u_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='u_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
