# Generated by Django 2.1.2 on 2018-10-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20181027_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
